### ISSUE TITLE
Add Fullscreen Videos via YouTube upon clicking play button on the website

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#107]
Maybe use Vime as player:
https://vimejs.com/getting-started/installation

**Comment by samuelandert** [comment]
@codeho 
Link für das erste Video:
- https://youtu.be/DO0BNzloqJU
Coverimage: /images/befree.jpg (bg-blue-900 mit opacity drüber legen, damit die Schrift erkennbar wird) 

Link Animationserklärvideo: 
- https://youtu.be/8wJbf8yLmRI
 Coverimage: Der erste Frame aus dem Weltall auf die Erde draufschauend

**Comment by codeho** [comment]
Video unavailable
This video has been removed by the uploader
