### ISSUE TITLE
make header bar of graph smaller

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#129]
<img width="1204" alt="Bildschirmfoto 2021-05-12 um 11 46 49" src="https://user-images.githubusercontent.com/747161/117954871-be1b1e00-b317-11eb-8f6a-d6097e5dd8c5.png">

**Comment by samuelandert** [comment]
and remove on focus

**Comment by samuelandert** [comment]
<img width="868" alt="Bildschirmfoto 2021-05-12 um 17 05 37" src="https://user-images.githubusercontent.com/747161/117998635-61822800-b344-11eb-84cf-a16e287440e6.png">
is it possible to make the graph content area full height?

**Comment by codeho** [comment]
done

**Comment by samuelandert** [comment]
![33641BF1-AAC8-4D79-B019-1EB647FB2A3E](https://user-images.githubusercontent.com/747161/118229751-d2345c00-b48c-11eb-9d71-4d8fe0a802a4.png)

It is still cut off at the bottom
