### ISSUE TITLE
Add Trust explain card on trusts route

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#135]

**Comment by samuelandert** [comment]
<img width="1364" alt="explaintrust" src="https://user-images.githubusercontent.com/747161/117969224-70a6ad00-b327-11eb-85da-7fd428400986.png">

In CirclesLand everyone has their own personalized Circles money. To be able to transfer Circles to someone you first need to get trusted by others. When you want to receive money you have to trust them back. Keep in mind always only connect yourself with people you trust and know in person. To transact with a stranger the network will calculate the flow of money for you.

Add button in the card with:  "copy my trust link"

**Comment by samuelandert** [comment]
@codeho 
Würde die karte in die trusts einbauen und oben pinnen (incl. bild)

**Comment by codeho** [comment]
Card added, @jaensen how can i get  'my trust link' ? so i can add this.
