### ISSUE TITLE
Hide skip and back buttons on all last Dialog steps when loading 

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#150]
![994DBE7F-7E32-464E-888C-F74DA186C909](https://user-images.githubusercontent.com/747161/118094506-1eb96200-b3cf-11eb-96a3-9f170697b46e.jpeg)

**Comment by codeho** [comment]
I guess we'd have to just hide this while the LoadingIndicator is active.
as this is not a separate view, we can't just not display it...
@jaensen can you help?
