### ISSUE TITLE
Sometimes the Trusts Route in banking nav is highlighted in a darker color

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#152]
![71BB7C93-7E21-4211-8F70-01FFBB6C1E0A](https://user-images.githubusercontent.com/747161/118094777-7952be00-b3cf-11eb-89c6-5a811e70a3ab.jpeg)

**Comment by codeho** [comment]
Could this be a cache thing? i can't reproduce it, i tried..

**Comment by codeho** [comment]
ah this happens when you tap on it, but then swipe away... i'll check
