### ISSUE TITLE
Add visual feedback for the 2 minute email login timeout

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#156]
If I open the login process again, it should automatically put me towards the "enter code" state, instead of starting a new process.

Also display the entered e-mail address again so that user can check it for typos.

- [ ] Style new HTML in "shell/src/dapps/o-passport/processes/identify/aquireSession/authenticate/authenticate.ts" line 233
- [ ] Check if the text is understandable and shorten it a bit if possible (@samuelandert )

**Comment by jaensen** [comment]
Display the entered e-mail address to the user:
![grafik](https://user-images.githubusercontent.com/4954577/118741843-8b10e700-b84f-11eb-9c9a-6cb0c19a96d1.png)

**Comment by jaensen** [comment]
Added a page that informs about the possible error conditions on login.
![grafik](https://user-images.githubusercontent.com/4954577/118742201-391c9100-b850-11eb-954b-b42cb53abc0d.png)
Its in desperate need of styling :)

**Comment by jaensen** [comment]
Added another error message that appears when a user enters the wrong code:
![grafik](https://user-images.githubusercontent.com/4954577/118744384-90bcfb80-b854-11eb-88bb-1eaa9d401a6c.png)
