### ISSUE TITLE
email magic login on localhost is broken

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#159]
I can not login anymore. 
Whenever I enter the magic login code, I get the email step again:
<img width="753" alt="Bildschirmfoto 2021-05-13 um 20 37 25" src="https://user-images.githubusercontent.com/747161/118170990-07a85d80-b42b-11eb-83d5-521d61636663.png">

**Comment by jaensen** [comment]
This should happen only when you're in private browsing mode. In this case, the cookie won't be stored.

**Comment by samuelandert** [comment]
This is only broken on localhost. Works perfectly on dev.circles.land... same browser settings, no private mode
