### ISSUE TITLE
If someone trusts me, and I dont trust them, show the oneway trust direction on the trust detail page

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#188]

**Comment by codeho** [comment]
Not sure but i think it's already doing that:

<img width="453" alt="Circles_Land" src="https://user-images.githubusercontent.com/40859/118478414-226f2080-b710-11eb-9714-9302b9655d04.png">

or do you mean something else?

**Comment by samuelandert** [comment]
ok, maybe this was a bug, I had once a state, where it was not displayed

**Comment by samuelandert** [comment]
this somehow is still not working:
<img width="957" alt="Bildschirmfoto 2021-05-19 um 12 13 39" src="https://user-images.githubusercontent.com/747161/118796182-a6094880-b89b-11eb-83f4-44785fc97560.png">

This is person is trusting me 50% and I dont trust back. 
It should show the 50% to me

**Comment by samuelandert** [comment]
ah, this is due to not refreshing the state. If I reenter the route its showing properly.
