### ISSUE TITLE
"Back" and "Skip" buttons are not aligned with the "Next" button

### ISSUE THREAD

**Issue by jaensen** [circlesland/o-platform#199]
![grafik](https://user-images.githubusercontent.com/4954577/118407613-d4abd700-b681-11eb-8a55-807aad671abc.png)

**Comment by codeho** [comment]
Maybe we can refactor that whole processnav/inside modal stuff.
i think it'd be cool if the actual app nav is its own component and the processnav is its own.
Otherwise, if we have the same containers for all these different elements, we're running into styling trouble like this one.

**Comment by samuelandert** [comment]
Jes, that’s actually the reason, we figured out that we need a cleanup and refactor week

**Comment by samuelandert** [comment]
Related to #198
