### ISSUE TITLE
Invite Button on profile page is not always shown when a safe is available

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#205]

**Comment by jaensen** [comment]
![Uploading grafik.png…]()

**Comment by jaensen** [comment]
![grafik](https://user-images.githubusercontent.com/4954577/118409976-6ec54c80-b68d-11eb-9505-40e12fc2cb0a.png)

**Comment by jaensen** [comment]
fixed with 1c496a5af518fde95a00cff3f7cf137c172c1e00
