### ISSUE TITLE
Make safe addresses on xDAI detail page highlight able

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#209]

**Comment by codeho** [comment]
please provide more information.

**Comment by samuelandert** [comment]
when I try to mark the safe text with the mouse its blocked and don't possible. Same goes for label texts in the dialog flows, which is kind of irritating

**Comment by codeho** [comment]
unfortunately i cannot change this without breaking the 'fade-out' solution for those cards.
we'd have to design some sort of context-menu on the card in which we can add a 'copy safe address' cta or something.
sorry

**Comment by samuelandert** [comment]
Got it, no problem
