### ISSUE TITLE
Add graph explorer to graph page of banking dapp, always set starting point to my user

### ISSUE THREAD

**Issue by jaensen** [circlesland/o-platform#24]

**Comment by samuelandert** [comment]
Make the content area full height

**Comment by jaensen** [comment]
@codeho I tried to give it a reasonable height up-front with css classes or style-attributes only to come up with this :)
```svelte
<div bind:this={graph} class="w-full -mt-56 pt-40" style="height:100vh;"></div>
```
The problem is, that the graph component creates a canvas that's based on the initial height of the div. So it needs to be set to a reasonable value on onMount() when the graph is created. After that the div contains a canvas with individual width and height attributes which won't adapt to the containing div after creation.
You'll need to do some research on the api of the graph component as they're usually provide a autoResize-flag or something similar or resort to some dirty hack..

**Comment by codeho** [comment]
@jaensen bei mir schauts jetzt gar nicht so schlecht aus. Allerdings hab ich halt nicht 'viele' nodes.
Gibts da ne möglichkeit für mich irgendwie an mehr nodes zu kommen? kann ich die faken irgendwie?

<img width="473" alt="Screenshot 2021-05-04 at 10 56 23" src="https://user-images.githubusercontent.com/40859/116981105-5fc2bf80-acc7-11eb-9fed-a2810ae3ed63.png">

**Comment by jaensen** [comment]
@codeho Du kannst beliebigen Leuten (z.B. allen denen wir trusten) trusten. Nur nicht vergessen den trust nach dem Test wieder zu entfernen :)

**Comment by codeho** [comment]
it is full height..

<img width="563" alt="Screenshot 2021-05-05 at 19 24 43" src="https://user-images.githubusercontent.com/40859/117183202-8f60ed00-add7-11eb-8871-f19d6ed176a8.png">
