### ISSUE TITLE
Website Content on mobile Safari is cut off at the bottom

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#249]
![93ABFA51-27E3-44AE-8213-B6153BA1AF74](https://user-images.githubusercontent.com/747161/118610811-746d8000-b7bc-11eb-94c8-fcb138f94b62.png)

**Comment by codeho** [comment]
This is also related to the bottom nav / process nav fix. once we did that, we can build a more stable sticky header/footer thing :)
