### ISSUE TITLE
Check if back buttons are displayed everywhere where its necessary

### ISSUE THREAD

**Issue by jaensen** [circlesland/o-platform#27]
Back (and skip) buttons are missing when a process was started from the homepage or via login-link. 
![grafik](https://user-images.githubusercontent.com/4954577/116284927-e9393580-a78d-11eb-980b-f45d566ae322.png)

**Comment by jaensen** [comment]
$me is not set during login so the minimal version of the button is displayed:
``` {#if !$me}
      <footer class="z-50  w-full sticky bottom-0 mb-2">
        <div class="flex justify-around ">
          <button
            class="mb-4 btn btn-outline bg-base-100"
            on:click={() => login("__APP_ID__")}
          >
            {#if !isOpen}
              <img
                width="15px"
                class="mr-3"
                src="/images/common/circles.png"
                alt="circles.land"
              /> login with circles
            {:else}
              <img
                width="15px"
                class="mr-3"
                src="/images/common/circles.png"
                alt="circles.land"
              /> Close
            {/if}
          </button>
        </div>
      </footer>
    {:else}
```

**Comment by codeho** [comment]
We may need to find a way to hide the circles button on certain pages (but we have to make sure it's only hidden if !isOpen in order to keep the [back] and [skip] fun)

**Comment by codeho** [comment]
TODO: hide back/skip during Load... (need to change loading behaviour anyways, so we'll wait with this and do it in one go)
<img width="703" alt="Screenshot 2021-04-28 at 01 48 29" src="https://user-images.githubusercontent.com/40859/116326071-e1948380-a7c3-11eb-9e1c-563b705a15aa.png">
