### ISSUE TITLE
My user in the graph page not centered. 

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#270]
![A51A6E7D-92E9-4E2A-BF23-DABF6136BBB3](https://user-images.githubusercontent.com/747161/118712129-b3352180-b820-11eb-903a-767c4d6d9005.png)

**Comment by codeho** [comment]
i'm sorry, i have to move this to @jaensen - i could not find in the slightest where i'd be able to adjust the position of the center user in that app...

**Comment by jaensen** [comment]
The node is perfectly centered within the graph but the graph component is not perfectly centered in its place.

Possible solution:
Wait until the page is fully loaded and then measure the size of the area where the graph should be displayed. 
Only after that initialize the graph with the previously measured dimensions. 
Display a loading spinner during the whole process and remove it when the graph was inserted at its position.
