### ISSUE TITLE
Compress and scale down profile images in the client (maybe 512x512?) 

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#272]
some users experience problems with their image upload. I think this might be related to being to large?

**Comment by codeho** [comment]
@samuelandert can you elaborate on the problems they're having?

**Comment by samuelandert** [comment]
one one trying to add a 1.4MB image, with 2600x2600 pixel and it didn't work. 
others reported similar problems. couldn't get more detail

**Comment by samuelandert** [comment]
I just tried a large picture with 2.1MB 4000x2700 and got this response:

<img width="569" alt="Bildschirmfoto 2021-05-19 um 16 18 02" src="https://user-images.githubusercontent.com/747161/118828703-cc3fe000-b8bd-11eb-9a2b-15da7defca2a.png">

**Comment by codeho** [comment]
can you attach the image so i can try

**Comment by samuelandert** [comment]
I think the client is still not down-sizing the image, before uploading. I just tried a large image and it didn't work. Smaller image was no problem.

**Comment by jaensen** [comment]
Can try if it fails on dev and main? How large was it?

**Comment by samuelandert** [comment]
it was on main. 2.1MB. will try dev now too

**Comment by samuelandert** [comment]
Did you deploy your fix on dev? the 2.1MB image didn't work on dev either.

**Comment by samuelandert** [comment]
I used this image
![jakob-owens-CTflmHHVrBM-unsplash](https://user-images.githubusercontent.com/747161/118945701-fcd35880-b955-11eb-9aa5-9efef5e4a854.jpg)
