### ISSUE TITLE
Profiles without lastname are displayed as "[firstname] null" on the transfer summary page

### ISSUE THREAD

**Issue by jaensen** [circlesland/o-platform#290]

**Comment by codeho** [comment]
i can't reproduce this..

<img width="404" alt="Screenshot 2021-05-19 at 19 21 47" src="https://user-images.githubusercontent.com/40859/118856731-8ee84c00-b8d7-11eb-9767-e40ce267af28.png">

**Comment by samuelandert** [comment]
<img width="1032" alt="Bildschirmfoto 2021-05-19 um 20 08 00" src="https://user-images.githubusercontent.com/747161/118862354-eab5d380-b8dd-11eb-8ba2-1a8fdbd744e0.png">
