### ISSUE TITLE
allow smartlinks to trigger transactions from other pages

### ISSUE THREAD

**Issue by jaensen** [circlesland/o-platform#31]
Use the same format as circles.garden: `https://circles.garden/send/[to-address]?a=[amount]&n=[message]`.
A logged on user should go directly to the summary page of a transaction in the safe. This will only work for CRC transactions although we could add another parameter to specify the token.

**Comment by jaensen** [comment]
- [ ] Create a new route in the banking-dapp (/#/banking/send/:to/:amount:message)
- [ ] Add a "export let params:{to:string, amount:string, message:string}" to the Transactions-Page
- [ ] onMount() or on changing parameters, check if at least "to" and "amount" have a value. If so, start the transfer process with these values pre-configured  

Caveats: Login- and safe-loading state must be checked

**Comment by codeho** [comment]
@jaensen should this then end up on the view where the user sees the pre-filled amount/currency field and has to submit, or should it end on the 'are you sure you want to transfer x.... to y.. ?

**Comment by codeho** [comment]
- [ ] Add direct route to 'confirm' etc. based on parameters.
