### ISSUE TITLE
Exchange "XXX" for safe address or name on sending invite credits

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#311]
![118951376-55592480-b95b-11eb-8072-cd50aefeb00f](https://user-images.githubusercontent.com/747161/118952273-17a8cb80-b95c-11eb-91e8-55c55bb231ab.png)

**Comment by codeho** [comment]
reassigning to @jaensen - this seems a more complicated thing than we thought. pls re-assign back once you need me to do something else on this.
