### ISSUE TITLE
Fix double scrollbar on website and inside dapps

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#328]
<img width="694" alt="Circles_Land_and_on_Website__fix_double_scrollbar_·_Issue__328_·_circlesland_o-platform" src="https://user-images.githubusercontent.com/40859/119128912-8b1f0b80-ba36-11eb-93ac-107c93297796.png">

**Comment by codeho** [comment]
please add example for double scrollbar within dapps.

**Comment by codeho** [comment]
okay so i can fix this by chaning the 'sticky' class in the footer to 'fixed', however the header/footer situation is still not behaving sexy enough on mobile safari. sometimes it pushes the header off the screen, and when the safari navigation ui pops up its still a bit wonky. i'd like to push this also back to after we extracted the footer from the process navigation.
then we can make this nice and clean and make sure it behaves the way it should everywhere.

**Comment by samuelandert** [comment]
Fine for me
