### ISSUE TITLE
Upgrade Ui from Trust Graph Explorer

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#342]
- [x] remove metadata trust percentage
- [ ] make arrows smaller 
- [x] make profile images larger
- [x] implement same profile image losing logic as everywhere else
- [x] fallback of username is safe address (don't show the safeaddress inside the image area)

**Comment by jaensen** [comment]
Couldn't find a quick way to change the arrow sizes. But since the images are larger now it might be o.k. already.
Arrow-examples: https://visjs.github.io/vis-network/examples/
