### ISSUE TITLE
Rethink narrative / text of the passion description field

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#345]
„What products or services will you offer in exchange for Circles to grow the basic income economy?“

And instead of „passion“ placeholder „I am offering ...“

und auf der Profile detail page:
„What I am offering in exchange for Circles“

**Comment by samuelandert** [comment]
@codeho  was meinst du? Dann werden das denke ich besser und qualitativere Aussagen

**Comment by codeho** [comment]
hmmm. @samuelandert ich weiss nicht, nicht dass die leute dann denken sie 'müssen' etwas anbieten um circles benutzen zu können...
