### ISSUE TITLE
On a "newer" samsung galaxy, the video on the starting page was not able to be played back

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#369]
I don't have more feedback to reproduce why or what the exact problem was. We pressed the play button, it went into fullscreen mode but didn't play

**Comment by codeho** [comment]
i don't have one...

**Comment by codeho** [comment]
agreed on waiting if there's reports coming in about this. couldn't reproduce on Samsung S21 Ultra Emulator. (Android 11 SDK 30)
