### ISSUE TITLE
New Dapps bottom navigation & refactor bottom navigation

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#387]
https://www.figma.com/file/CG86Zm5IE4v3DHQTe12CDk/CirclesLand?node-id=167%3A10

**Comment by samuelandert** [comment]
![89B138A5-79F6-41C2-B890-55C0FB61FF73](https://user-images.githubusercontent.com/747161/120340920-b89d6c00-c2f6-11eb-897d-f123bb5f8e76.png)
Fix the bottom Padding and side padding on iOS devices without home bottom

**Comment by jaensen** [comment]
the nav dots are not implemented
