### ISSUE TITLE
RPC Gateway dying a lot

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#40]
For some reason it keeps losing the set safe... 

<img width="1148" alt="Screenshot 2021-04-29 at 11 23 23" src="https://user-images.githubusercontent.com/40859/116529491-50b1cb00-a8dd-11eb-9eb1-5048ddf9051f.png">

**Comment by jaensen** [comment]
This happens periodically due to inactivity on the websocket. Nonetheless we need current events so it reconnects in this cases (and rotates the provider). I think we can only solve this with an own rpc gateway (if we set it up right ;)

**Comment by jaensen** [comment]
I set up an own gateway and rotate between it and the public gateway. 
The mentioned errors will stay because our gateway closes websocket connections after an idle time too.
