### ISSUE TITLE
Query Injection möglich bei suche

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#41]
Könnte evtl. zu performance problemen führen, wenn wir sehr viele user haben:

<img width="416" alt="Screenshot 2021-04-29 at 13 02 59" src="https://user-images.githubusercontent.com/40859/116541049-3d0d6100-a8eb-11eb-9ec4-d10bef7eda42.png">

**Comment by jaensen** [comment]
Ist auf 100 Ergebnisse begrenzt und es werden nur indexierte Felder abgefragt. Außerdem können diese Queries auf der read-only Instanz ausgeführt werden und es gibt ein rate-limit für die Api. Sollte kein allzugroßes Problem sein.
