### ISSUE TITLE
Market Checkout Flow

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#474]
Checkout Summary Page
- [x] add Items
- [x] add Seller Address
- [x] add Items Pickup at store info card
- [x] add connection to 'purchases' table
- [x] add errormessaging

Checkout Confirmation Page
- [x] standard transfer confirmation content
- [x] Store pickup information (Pickup Code)
- [x] Contact seller (chat button)
- [x] after close don't re-open cart.
- [x] #476 

Checkout Process
- [x] create Purchase
- [x] wait for transaction hash
- [x] confirm transaction
- [x] create purchase

**Comment by jaensen** [comment]
Isn't blocked anymore for direct trusts: https://github.com/circlesland/o-platform/issues/516
