### ISSUE TITLE
Generate PDF Invoice for Purchase

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#476]
- [x] investigate pdf kit
- [x] get local encapsulated version running
- [x] implement sales tax
- [x] add to repo code
- [ ] #523
- [ ] #524
- [ ] #525

**Comment by samuelandert** [comment]
Inspiration: 

https://pspdfkit.com/blog/2019/generate-invoices-pdfkit-node/

**Comment by codeho** [comment]
add umsatzsteuer

**Comment by codeho** [comment]
So far so good. now waiting for #474 to implement further.

**Comment by jaensen** [comment]
Isn't blocked anymore for direct trusts: https://github.com/circlesland/o-platform/issues/516

**Comment by codeho** [comment]
invoice generator in o-platform.... shared/processes/generateInvoice.ts
