### ISSUE TITLE
Market My Purchases

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#477]
**My Purchases List**
- [x] Display my purchases
- [x] Link to purchase Detail

**Purchase Detail**
- [x] Show all details as neccessary
- [x] Show Pickup Code

**Comment by codeho** [comment]
@jaensen ive tried adding the profile to the offer here, but it didn't work. could you have a look?

`... on Purchases {
        lastUpdatedAt
        purchases {
          id
          createdAt
          createdByAddress
          createdByProfile {
            id
            firstName
            lastName
            avatarCid
          }
          total
          lines {
            id
            amount
            offer {
              id
              version
              title
              description
              pictureUrl
              pricePerUnit
              createdByProfile {
                id
                circlesAddress
                firstName
                lastName
                avatarUrl
              }
            }
          }
        }
      }`

**Comment by jaensen** [comment]
@codeho The profile is now available

**Comment by jaensen** [comment]
Isn't blocked anymore for direct trusts: https://github.com/circlesland/o-platform/issues/516
