### ISSUE TITLE
Design content of xDAI detail page

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#49]

**Comment by codeho** [comment]
@samuelandert can you attach your scribble?

**Comment by samuelandert** [comment]
don't have it at hand at the moment. its in the office. 

basically the idea was to have one xDai card on the assets overview (@jaensen showing a total combined balance), and then click into the xdai detail page, which displays the two balances separately.

TOP CARD:
left: xDai icon, 
top text: "Safeowner", 
bottom text: "0xasdifusd798 (safe owner address)", 
right text: safe owner xdai balance,
right bottom text: calculate the average transactions left, you can do with this balance, (0,01 ~ 300-500 transactions)

BOTTOM CARD:
left: xDai icon, 
top text: "Safe", 
bottom text: "0x967a9dsgdfoasdui (safe address)", 
right text: safe xdai balance,
right bottom text: calculate the invites left, which you can do with this balance (balance * 10)

**Comment by codeho** [comment]
@jaensen how do i get the xdai balances for those?

**Comment by samuelandert** [comment]
The two xDAI balances are already there. they just have to be moved to the details page. 

The only balance missing, is the sum of the two, on the overview
