### ISSUE TITLE
Trust / Untrust / retrust states are sometimes not correctly updated

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#513]
- [x] bug 1

I trusted Martin, untrusted martin and retrusted Martin again. so it supposed to be mutual trust, but it isn't
<img width="1161" alt="Bildschirmfoto 2021-11-16 um 16 42 37" src="https://user-images.githubusercontent.com/747161/142017304-07db2aba-8084-4b56-8e21-d777fa9fcf32.png">

<img width="939" alt="Bildschirmfoto 2021-11-16 um 16 44 26" src="https://user-images.githubusercontent.com/747161/142017579-7b0c5de4-6931-4fec-8d51-d7b0c114e07a.png">

- [x] bug 2
the mutual trust friends on a profile card are not correctly filtered too: 
f.e. GOD trusts me, but I dont trust GOD (thus should be filtered out of the view)
<img width="570" alt="Bildschirmfoto 2021-11-16 um 16 46 34" src="https://user-images.githubusercontent.com/747161/142017980-bb49cd8a-4f00-45c8-ad0f-86664609abea.png">

<img width="1058" alt="Bildschirmfoto 2021-11-16 um 16 47 20" src="https://user-images.githubusercontent.com/747161/142018093-7f545e12-9935-4a1b-8431-08aae45fb403.png">

as well as orgas should be filtered out too, since they can only trust "one-way"
<img width="428" alt="Bildschirmfoto 2021-11-16 um 16 47 39" src="https://user-images.githubusercontent.com/747161/142018139-eb7a26fe-109e-44b2-8b0b-3f2dde719ca8.png">

in the mutual trusts view, there should only be profiles displayed, where it is matching 2 criteria's, 

1) i trust shared friend, shared friends trusts me
2) martin trusts shared friend, shared friend trusts Martin

- [ ] orga follow trust is affected of this swell 

- [ ] feature request 4
Lets make a second area with friends "Martin" is having mutual trust connections with, that I don't have yet. 
f.e. 
martin trusts person x, person x trusts martin ( I don't trust friend x yet, but I know friend x, so I can start trusting friend x, when I click on his avatar)

**Comment by jaensen** [comment]
should be fixed with 61eb6bb7e335b3adb9537ce2d21a1270613b94bc
