### ISSUE TITLE
Market - Purchases / Sales Cards / Detail Status

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#526]
Display status flags on Purchase card / detail

Stati:
- [x] Transaction Succes / Failed
- [x] pickup code available
- [x] Picked up confirmed by seller
- [x] Picked up confirmed by buyer
- [x] Refund requested 
- [x] Refund granted
- [x] Refund rejected 
- [x] Refund complete

**Comment by jaensen** [comment]
Added the status to the list cards. See: https://github.com/circlesland/o-platform/issues/527
