### ISSUE TITLE
Market - My Sales - API: Add Pickup Confirm Functionality

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#527]
Add 'Confirm PickUp' functionality to the Purchases Object/Db/Thing.
and some sort of upsertPurchase for the Seller to mark a purchase as 'picked up'.

**Comment by jaensen** [comment]
I added a completePurchase() (customer side) and completeSale() (seller side) mutation.
The "signatures" are attached to the invoice. It has the following new properties: buyerAddress, pickupCode, buyerSignature, buyerSignedDate

**Comment by jaensen** [comment]
I added a corresponding action to the SalesDetail and PurchaseDetail page. Needs some more love.

**Comment by jaensen** [comment]
the actions must be converted to a process so that we can show any errors in the default error dialog.
