### ISSUE TITLE
TimeCircles: Too many decimal places to convert to wei

### ISSUE THREAD

**Issue by jaensen** [circlesland/o-platform#535]
![grafik](https://user-images.githubusercontent.com/4954577/142623427-e609e858-ca87-42b0-9ca9-70450c4a0db3.png)

**Comment by jaensen** [comment]
Martin experienced a similar Problem when he opens the chat overview:
![grafik](https://user-images.githubusercontent.com/4954577/142642503-7454f4ca-c9c2-4127-8e9a-57c25b64406c.png)

**Comment by samuelandert** [comment]
same happens, when trying to purchase something for 0.01 TCRC
<img width="958" alt="Bildschirmfoto 2021-11-22 um 13 23 19" src="https://user-images.githubusercontent.com/747161/142861210-20729e4e-2821-4b3a-a016-ef271286a701.png">

**Comment by codeho** [comment]
@samuelandert @jaensen to be honest, i'd like to move this back until we've done the 'euro' display stuff.
as most of this is gonna change with it anyways.
