### ISSUE TITLE
Invitations: if invitation redemption error (not funded etc..) need option to enter new code

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#551]
currently if the user enters an invitation code thats not funded, he won't be able to continue at all,
even he has a new code, as he will jump right into 'REDEEM YOUR INVITATION' process.

it'd be good to be able to add a new code at this point

Maybe it makes sense to do the 'is Funded' check in the 'verify' function, and if it's not, throw the user back to the 'enter code' screen.

**Comment by samuelandert** [comment]
Maybe lets solve this with just a link, instead of entering the code manually.
