### ISSUE TITLE
Improve contacts / friends / network / chat dapp overviews 

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#553]
- [x] Rename the friends dapp to chat
- [x] Please sort by alphabet (with the exception of putting 0x124134 addresses to the end)

**Comment by codeho** [comment]
Maybe add a switch for in between friends & chat
<img width="489" alt="switch" src="https://user-images.githubusercontent.com/40859/143418228-25157888-f760-4eb8-b74b-c9f3adb12d22.png">

**Comment by samuelandert** [comment]
@codeho can you sort the contacts by alphabet (with the exception of putting 0x124134 addresses to the end)
