### ISSUE TITLE
The marketplace checkout requires co-payment x% TIME / x% HUMAN  via db (initial rate 1€ : 10 Time)

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#572]
- [x] Add percentage fields to db and according gql stuff.
- [x] Add this data to offer, purchase, sale objects
- [ ] display on Offercard, offer detail, purchases/sales cards, invoice, other communications(notifications)
- [ ] update calculations in shopping Cart and buying pipeline views.

Data: (hardcode)
1. Mundgranate - 2€ (100% ⦿, 20 TIME) 
2. Chukalaka (Rotwein) - 10€ (50%⦿, 5€ (HMN) + 50 TIME) 
3. Chukalina (Weißwein) - 10€ (50%⦿, 5€ (HMN) + 50 TIME)
4. Katha Schnatta (Gin) - 40€ (50%⦿, 20€ (HMN) + 200 TIME)
5. Bavarian Barbarian (Beer) - 2€ (50%⦿, 1€ (HMN) + 10 TIME)

**Comment by jaensen** [comment]
The "timeCirclesPriceShare" is available on the "Offer" type and thus also on the invoice- and purchase-lines
