### ISSUE TITLE
Define the Verification/Invite/Reward parameters

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#573]
DEV/TEST Environment variables
- [x] clean up all xdai constants f.e.
    - [x] 0,01 xdai per invite, 
    - [ ] create only 1 invite per verification
    - [ ] unlimited invites for ambassadors (Test Orga members)
    
- [ ] use TestOrga for only test members
- [ ] implement test human token constants (tokenaddress)

Tor.us
- [ ] use old daniel key

EOA's and Safes
- [ ] invite xdai + test human Safe (fill in safe address)

HUMAN Payouts safes:
- [ ] verification provider (separate verificator reward safe) 10%
- [ ] invitee 70%
- [ ] inviter 20%

**Comment by jaensen** [comment]
- [ ] Lazily fund the invitations when the code was claimed.
- [ ] 9 invites for everybody who's verified
