### ISSUE TITLE
Add Welcome event & Notification View

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#611]
- [ ] @samuelandert please provide text for welcome notification
- [ ] 
- [x] jaensen: check if welcome event is being sent
- [x] thorsten: add view
- [ ] add X invited you 'do you want to trust him'?
- [ ] doublecheck all notification Actions (buttons)

**Comment by jaensen** [comment]
You can test the notification either by creation a new account or by resetting your profile's "lastAcknowledged" date to the beginning of time ;)
