### ISSUE TITLE
update terms und privacy

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#634]
beides jeweils auf home und dem dashboard

<img width="683" alt="Bildschirmfoto 2021-12-17 um 11 13 31" src="https://user-images.githubusercontent.com/747161/146528478-02717140-0c2b-4096-b0d5-54bb6ea9348f.png">

- [x] forum link auch noch mal gerne updaten:

https://aboutcircles.com/c/earth-circle-dao/13

- [x] privacy policy:
https://coda.io/@circlesland/terms/privacy-policy-3

- [x] terms:
https://coda.io/@circlesland/terms

- [x] add both links as well during the account creation onboarding flow

**Comment by codeho** [comment]
when the process popup is open we can't show the navigation. 
ppl will only see it when the popup is closed.
