### ISSUE TITLE
on redeem invite page add 'logout' link in case user gets stuck.

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#662]
- [ ] on redeem invite page add 'logout' link in case user gets stuck.

**Comment by samuelandert** [comment]
Let’s always clear the storage, when pressing x, when the user is stuck on the invite screen

**Comment by codeho** [comment]
@jaensen Can we add the behaviour, that when a user clicks on the X on the 'enter your invitation' page, it triggers a logout?
that would be the cleanest solution.
