### ISSUE TITLE
send 'verify-your-email' mail to email address [backend]

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#698]
- [x] add verified-email flag to Profile - default false
- [x] add verification table: random-code, created_at, valid_to, profile_id
- [x] add mail sender to send to email address using 'verify-your-email' template
- [x] add verification route
- [x] check verification table if code is valid
- [ ] #706
  - [x] add redirect url to redirect to after successful
- [ ] #707

**Comment by jaensen** [comment]
@codeho I need a route to an error- and success-page in the client. The server sends the user there with a 302 response.
