### ISSUE TITLE
Marketplace Location Filter Group Ticket

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#709]
- [x] Get Offers for Orga
- [x] Get All Orgas that have products
- [x] Add you trusted state to the Orga object.
- [x] Add Orga Page, show all Orga which are trusting the currentUser, link to OrgaOffers 
- [x] Add OrgaOffers Page, list all Offers for set Location (check trusted status on direct url)
- [x] Add List-view for offers

- [x] Do we have 'Organisation XYZ trusted you...' Events?

**Comment by jaensen** [comment]
* Get All Orgas that have products
query {
  organisationsWithOffers {
    name
    circlesAddress
    offers {
      id
      title
    }
  }
}
