### ISSUE TITLE
change default profile image back to avataaaars generator api

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#72]
https://getavataaars.com

**Comment by samuelandert** [comment]
use the "profiles safe" address as random generator input

**Comment by codeho** [comment]
@samuelandert  how would we determine if we should generate a male or female character?

**Comment by samuelandert** [comment]
We don't 😂 if they are not happy with their generated profile, they have to upload something else. ✌️

**Comment by codeho** [comment]
@jaensen where can i find the code for where we had this before? it'll save me some time :)

**Comment by samuelandert** [comment]
not finished, as we need to support non circlesland users

**Comment by jaensen** [comment]
Another problem is that we don't know the safeOwner- or safe-Address during the first profile creation (directly after the first login) so we don't have a seed for the generator at this point.
Fallback: Use the e-mail address for our own users and the safe address for others?

**Comment by jaensen** [comment]
Now tracked in #96
