### ISSUE TITLE
the profile image on the trust / user detail page is wrong

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#79]
<img width="696" alt="Bildschirmfoto 2021-05-04 um 17 32 36" src="https://user-images.githubusercontent.com/747161/117029211-b8fa1580-acfe-11eb-9a8d-0a4a2a917807.png">

**Comment by codeho** [comment]
that was the default image for when someone has no image. this is fixed now with the avataaars thing.
there's also a fallback avataaar.
