### ISSUE TITLE
Fix margin on IOS when keyboard is coming up

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#80]
wenn die Tastatur auf iOS hochfährt klemmt er irgendwie unten beim den Buttons ein bisschen margin weg
![IMAGE 2021-05-05 13:19:34](https://user-images.githubusercontent.com/747161/117133442-899de400-ada4-11eb-9234-acfc86421ae4.jpg)

**Comment by codeho** [comment]
yes. unfortunately that is a known bug. i can hack-fix this by detecting the on:focus event, and then push up the whole site, but i have to check with @jaensen about how to catch the on:focus event in App. svelte through bubbling up via the ProcessContainer and all that..
