### ISSUE TITLE
Final Content For Signup / Identity processes

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#88]

**Comment by codeho** [comment]
Pls have a check on the final text for all the pipelines, because based on the size of the text, i have to find a solution for mobile.  
In this example, because we have auto-focus on the input fields, the mobile keyboard pops up immediately when the view loads, so the user has no chance to actually read all the text:

![Screenshot 2021-05-07 at 12.23.22.png](https://app.gitkraken.com/api/glo/boards/609474c6054f9d00125ffb17/attachments/6095151f214da50011c0eca1)

**Comment by samuelandert** [comment]
I think autopopup on mobile of the keyboard is not a nice user experience. There will be several steps, that require more explanation text. So as starting point on mobile, its always good to have to fullscreen with each step and only popup the keyboard, upon manual entry. 
I think you can try to make both fonts tiny bit smaller again, to cover most of the cases, even with the keyboard out.
